days_with_header_images = [
  {'key': 'freckles_day', 'day': 'Dzień Piegów', 'images': ['dziecko z piegami', 'lupa', 'lustro z uśmiechniętą twarzą dziecka']},
  {'key': 'dinosaur_day', 'day': 'Dzień Dinozaura', 'images': ['tyranozaur', 'triceratops', 'jajko dinozaura']},
  {'key': 'barbie_day', 'day': 'Dzień Barbie', 'images': ['lalka Barbie', 'różowy samochód', 'szafa z ubraniami']},
  {'key': 'butterfly_day', 'day': 'Dzień Motyli', 'images': ['motyl monarcha', 'motyl na kwiatach', 'dziecko z siatką na motyle']},
  {'key': 'carrot_day', 'day': 'Dzień Marchewki', 'images': ['marchewka', 'królik', 'koszyk warzyw']},
  {'key': 'rainbow_day', 'day': 'Dzień Tęczy', 'images': ['tęcza na niebie', 'dziecko z parasolką', 'chmury']},
  {'key': 'chocolate_day', 'day': 'Dzień Czekolady', 'images': ['czekolada mleczna', 'tabliczka czekolady', 'kakao']},
  {'key': 'dolphin_day', 'day': 'Dzień Delfina', 'images': ['delfin wyskakujący z wody', 'dzieci obserwujące delfiny', 'ocean']},
  {'key': 'tree_day', 'day': 'Dzień Drzewa', 'images': ['drzewo w lesie', 'dziecko sadzące drzewo', 'jesienne liście']},
  {'key': 'horse_day', 'day': 'Dzień Koni', 'images': ['koń galopujący', 'dziecko na kucyku', 'stajnia']},
  {'key': 'firefighter_day', 'day': 'Dzień Strażaka', 'images': ['strażak z wężem', 'wóz strażacki', 'płonący domek (symbolicznie)']},
  {'key': 'bee_day', 'day': 'Dzień Pszczół', 'images': ['pszczoła na kwiatku', 'ul', 'dziecko w stroju pszczoły']},
  {'key': 'space_day', 'day': 'Dzień Kosmosu', 'images': ['planety', 'dziecko w skafandrze', 'rakieta']},
  {'key': 'turtle_day', 'day': 'Dzień Żółwia', 'images': ['żółw lądowy', 'żółw morski', 'dziecko obserwujące żółwia']},
  {'key': 'snail_day', 'day': 'Dzień Ślimaka', 'images': ['ślimak z muszlą', 'dziecko obserwujące ślimaka', 'mokry liść']},
  {'key': 'children_day', 'day': 'Dzień Dziecka', 'images': ['dzieci bawiące się', 'zabawki', 'kolorowe balony']},
  {'key': 'ocean_day', 'day': 'Dzień Oceanów', 'images': ['rafa koralowa', 'ryby', 'dziecko nurkujące z maską']},
  {'key': 'giraffe_day', 'day': 'Dzień Żyrafy', 'images': ['żyrafa', 'dziecko w zoo', 'drzewo akacji']},
  {'key': 'smurf_day', 'day': 'Dzień Smerfa', 'images': ['Smerf Ważniak', 'Wioska Smerfów', 'Gruby Smerf']},
  {'key': 'mutt_day', 'day': 'Dzień Kundelka', 'images': ['kundelek', 'budka dla psa', 'dziecko głaszczące psa']},
  {'key': 'pumpkin_day', 'day': 'Święto Dyni', 'images': ['dynia halloweenowa', 'dziecko z dynią', 'pole dyniowe']},
  {'key': 'fairy_tale_characters_day', 'day': 'Dzień Postaci z Bajek', 'images': ['Shrek', 'Elsa z Krainy Lodu', 'Minionek']},
  {'key': 'hedgehog_day', 'day': 'Dzień Jeża', 'images': ['jeż w trawie', 'jeż z jabłkiem', 'dziecko rysujące jeża']},
  {'key': 'crayon_day', 'day': 'Dzień Kredki', 'images': ['kredki w piórniku', 'dziecko rysujące', 'kolorowe rysunki']},
  {'key': 'falling_leaf_day', 'day': 'Dzień Spadającego Liścia', 'images': ['liść klonu', 'dziecko rzucające liście', 'jesienne drzewo']},
  {'key': 'smile_day', 'day': 'Dzień Uśmiechu', 'images': ['dziecko uśmiechnięte', 'słońce', 'uśmiechnięta buźka']},
  {'key': 'origami_day', 'day': 'Dzień Origami', 'images': ['papierowe żurawie', 'dziecko składające origami', 'kolorowe kartki']},
  {'key': 'skirt_day', 'day': 'Dzień Spódnicy', 'images': ['dziewczynka w spódnicy', 'falbany', 'wirująca spódnica']},
  {'key': 'black_cat_day', 'day': 'Dzień Czarnego Kota', 'images': ['czarny kot', 'dziecko z kotem', 'księżyc']},
  {'key': 'teddy_bear_day', 'day': 'Dzień Pluszowego Misia', 'images': ['pluszowy miś', 'dziecko z misiem', 'łóżko z pluszakami']}
]
